/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'
import { Route as ImgSplatRouteImport } from './routes/img.$'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAuthedRouteImport } from './routes/admin/_authed'
import { Route as AdminAuthedIndexRouteImport } from './routes/admin/_authed/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminAuthedProduitsRouteImport } from './routes/admin/_authed/produits'
import { Route as AdminAuthedParametresRouteImport } from './routes/admin/_authed/parametres'
import { Route as AdminAuthedCategoriesRouteImport } from './routes/admin/_authed/categories'
import { Route as AdminAuthedProduitsIdRouteImport } from './routes/admin/_authed/produits.$id'

const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ImgSplatRoute = ImgSplatRouteImport.update({
  id: '/img/$',
  path: '/img/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedRoute = AdminAuthedRouteImport.update({
  id: '/admin/_authed',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedIndexRoute = AdminAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedProduitsRoute = AdminAuthedProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedParametresRoute = AdminAuthedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedCategoriesRoute = AdminAuthedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedProduitsIdRoute = AdminAuthedProduitsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAuthedProduitsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/admin': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/img/$': typeof ImgSplatRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin/categories': typeof AdminAuthedCategoriesRoute
  '/admin/parametres': typeof AdminAuthedParametresRoute
  '/admin/produits': typeof AdminAuthedProduitsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AdminAuthedIndexRoute
  '/admin/produits/$id': typeof AdminAuthedProduitsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/admin/login': typeof AdminLoginRoute
  '/img/$': typeof ImgSplatRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin/categories': typeof AdminAuthedCategoriesRoute
  '/admin/parametres': typeof AdminAuthedParametresRoute
  '/admin/produits': typeof AdminAuthedProduitsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AdminAuthedIndexRoute
  '/admin/produits/$id': typeof AdminAuthedProduitsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/admin/_authed': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/img/$': typeof ImgSplatRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin/_authed/categories': typeof AdminAuthedCategoriesRoute
  '/admin/_authed/parametres': typeof AdminAuthedParametresRoute
  '/admin/_authed/produits': typeof AdminAuthedProduitsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/_authed/': typeof AdminAuthedIndexRoute
  '/admin/_authed/produits/$id': typeof AdminAuthedProduitsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogue'
    | '/contact'
    | '/devis'
    | '/admin'
    | '/admin/login'
    | '/img/$'
    | '/produit/$slug'
    | '/admin/categories'
    | '/admin/parametres'
    | '/admin/produits'
    | '/api/auth/$'
    | '/admin/'
    | '/admin/produits/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogue'
    | '/contact'
    | '/devis'
    | '/admin/login'
    | '/img/$'
    | '/produit/$slug'
    | '/admin/categories'
    | '/admin/parametres'
    | '/admin/produits'
    | '/api/auth/$'
    | '/admin'
    | '/admin/produits/$id'
  id:
    | '__root__'
    | '/'
    | '/catalogue'
    | '/contact'
    | '/devis'
    | '/admin/_authed'
    | '/admin/login'
    | '/img/$'
    | '/produit/$slug'
    | '/admin/_authed/categories'
    | '/admin/_authed/parametres'
    | '/admin/_authed/produits'
    | '/api/auth/$'
    | '/admin/_authed/'
    | '/admin/_authed/produits/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogueRoute: typeof CatalogueRoute
  ContactRoute: typeof ContactRoute
  DevisRoute: typeof DevisRoute
  AdminAuthedRoute: typeof AdminAuthedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ImgSplatRoute: typeof ImgSplatRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/img/$': {
      id: '/img/$'
      path: '/img/$'
      fullPath: '/img/$'
      preLoaderRoute: typeof ImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed': {
      id: '/admin/_authed'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed/': {
      id: '/admin/_authed/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthedIndexRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed/produits': {
      id: '/admin/_authed/produits'
      path: '/produits'
      fullPath: '/admin/produits'
      preLoaderRoute: typeof AdminAuthedProduitsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/parametres': {
      id: '/admin/_authed/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminAuthedParametresRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/categories': {
      id: '/admin/_authed/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminAuthedCategoriesRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/produits/$id': {
      id: '/admin/_authed/produits/$id'
      path: '/$id'
      fullPath: '/admin/produits/$id'
      preLoaderRoute: typeof AdminAuthedProduitsIdRouteImport
      parentRoute: typeof AdminAuthedProduitsRoute
    }
  }
}

interface AdminAuthedProduitsRouteChildren {
  AdminAuthedProduitsIdRoute: typeof AdminAuthedProduitsIdRoute
}

const AdminAuthedProduitsRouteChildren: AdminAuthedProduitsRouteChildren = {
  AdminAuthedProduitsIdRoute: AdminAuthedProduitsIdRoute,
}

const AdminAuthedProduitsRouteWithChildren =
  AdminAuthedProduitsRoute._addFileChildren(AdminAuthedProduitsRouteChildren)

interface AdminAuthedRouteChildren {
  AdminAuthedCategoriesRoute: typeof AdminAuthedCategoriesRoute
  AdminAuthedParametresRoute: typeof AdminAuthedParametresRoute
  AdminAuthedProduitsRoute: typeof AdminAuthedProduitsRouteWithChildren
  AdminAuthedIndexRoute: typeof AdminAuthedIndexRoute
}

const AdminAuthedRouteChildren: AdminAuthedRouteChildren = {
  AdminAuthedCategoriesRoute: AdminAuthedCategoriesRoute,
  AdminAuthedParametresRoute: AdminAuthedParametresRoute,
  AdminAuthedProduitsRoute: AdminAuthedProduitsRouteWithChildren,
  AdminAuthedIndexRoute: AdminAuthedIndexRoute,
}

const AdminAuthedRouteWithChildren = AdminAuthedRoute._addFileChildren(
  AdminAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogueRoute: CatalogueRoute,
  ContactRoute: ContactRoute,
  DevisRoute: DevisRoute,
  AdminAuthedRoute: AdminAuthedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ImgSplatRoute: ImgSplatRoute,
  ProduitSlugRoute: ProduitSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
